controller_names:
  - joint_trajectory_controller


joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - omron/joint_1
    - omron/joint_2
    - omron/joint_3
    - omron/joint_4
    - omron/joint_5
    - omron/joint_6
