teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 0
      y: 1
      z: 7
    scale_linear:
      x: 0.1
      y: 0.1
      z: 0.1
    axis_angular:
      roll: 3
      yaw: 4
    scale_angular:
      roll: 0.1
      yaw: 0.1
    enable_button: 5
    enable_turbo_button: 8
