omron:
  controller_manager:
    ros__parameters:
      update_rate: 10  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      # io_and_status_controller:
        # type: ur_controllers/GPIOController

      # force_torque_sensor_broadcaster:
        # type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      # my_cartesian_motion_controller:
      #   type: "cartesian_motion_controller/CartesianMotionController"
        
      imm:
        type: imm_controller/ImmController


omron:
  joint_trajectory_controller:
    ros__parameters:
      joints:
        - omron/joint_1
        - omron/joint_2
        - omron/joint_3
        - omron/joint_4
        - omron/joint_5
        - omron/joint_6
      command_interfaces:
        - position
      state_interfaces:
        - position
        # - velocity
      state_publish_rate: 125.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      constraints:
        stopped_velocity_tolerance: 0.1
        goal_time: 0.0
        joint_1: { trajectory: 10.1, goal: 0.1 }
        joint_2: { trajectory: 10.1, goal: 0.1 }
        joint_3: { trajectory: 10.1, goal: 0.1 }
        joint_4: { trajectory: 10.1, goal: 0.1 }
        joint_5: { trajectory: 10.1, goal: 0.1 }
        joint_6: { trajectory: 10.1, goal: 0.1 }

omron:
  imm:
    ros__parameters:
      command_joints:
        - omron/joint_1
        - omron/joint_2
        - omron/joint_3
        - omron/joint_4
        - omron/joint_5
        - omron/joint_6
      joints:
        - omron/joint_1
        - omron/joint_2
        - omron/joint_3
        - omron/joint_4
        - omron/joint_5
        - omron/joint_6
      control_interface:
      - position
      state_interface:
      - position
      - velocity
      robot_chain_root: omron/base
      robot_chain_tip:  omron/flange
      amr_base_link:  omron/base_link
      cmd_vel_topic: /omron/cmd_vel
      robot_description_topic: /omron/robot_description
      only_robot: true
      omni: false

# my_cartesian_motion_controller:
#   ros__parameters:
#     end_effector_link: "omron/flange"
#     robot_base_link: "omron/base"
#     target_frame_topic: "target_frame"
#     joints:
#         - omron/joint_1
#         - omron/joint_2
#         - omron/joint_3
#         - omron/joint_4
#         - omron/joint_5
#         - omron/joint_6
    
#     command_interfaces:
#       - position

#     solver:
#       error_scale: 2.0
#       iterations: 25

#     pd_gains:
#         trans_x: {p: 1.2} #,d: 0.0001}
#         trans_y: {p: 1.2} #,d: 0.0001}
#         trans_z: {p: 1.2} #,d: 0.0001}
#         rot_x:   {p: 0.5} #,d: 0.0005}
#         rot_y:   {p: 0.5} #,d: 0.0005}
#         rot_z:   {p: 0.5} #,d: 0.0005}
